In [ ]:
# main

In [3]:
# 1. Handle Data
import pandas as pd

df=pd.read_csv('iris.data.txt',sep=',',names = ['a','b','c','d','e'])
df

       a    b    c    d               e
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
#Converting categorical to numerical so we can use knn
df['e']=df['e'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})

#Choosing the features as x and the target as y
x=df[['a','b','c','d']]
y=df['e']
df

       a    b    c    d  e
0    5.1  3.5  1.4  0.2  0
1    4.9  3.0  1.4  0.2  0
2    4.7  3.2  1.3  0.2  0
3    4.6  3.1  1.5  0.2  0
4    5.0  3.6  1.4  0.2  0
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  2
146  6.3  2.5  5.0  1.9  2
147  6.5  3.0  5.2  2.0  2
148  6.2  3.4  5.4  2.3  2
149  5.9  3.0  5.1  1.8  2

[150 rows x 5 columns]

In [9]:
# Next we need to split the data into a training dataset 
import csv
import random
def loadDataset(filename, split, trainingSet=[] , testSet=[]):
 with open(filename, 'r') as csvfile:
    lines = csv.reader(csvfile)
    dataset = list(lines)
    for x in range(len(dataset)):
        for y in range(4):
            dataset[x][y] = float(dataset[x][y])
        if random.random() < split: # 0.66
           # complete code
           trainingSet.append(dataset[x])  # dataset[x] c une ligne
        else:
          #  complete code
           testSet.append(dataset[x])
        
#We can test this function out with our iris dataset, as follows:
trainingSet=[]
testSet=[]
loadDataset('iris.data.txt', 0.66, trainingSet, testSet)
print ('Train: ' + repr(len(trainingSet)))
print ('Test: ' + repr(len(testSet)) )

Train: 97
Test: 53

In [25]:
# Simularity
import math
def euclideanDistance(instance1, instance2, length):
    somme = 0
    for i in range(length) :
        somme += math.pow(instance1[i]-instance2[i],2) 
    RES = math.sqrt(somme)
    return RES

def manhattanDistance(instance1, instance2, length):
    somme = 0
    for i in range(length) :
        somme += abs(instance1[i]-instance2[i])
    return somme
# Note here that number of elements in the instance1 =number of elements in the instance2 
# the length refers to the number of elements in the instance1 
# We can test this function with some sample data, as follows:

data1 = [2, 2, 2, 'a']
data2 = [4, 4, 4, 'b']
distance = manhattanDistance(data1, data2, 3)

print ('Distance: ' + repr(distance))

Distance: 6

In [19]:
import operator 
def getNeighbors(trainingSet, testInstance, k):
    distances = []
    length = len(testInstance)-1
    for x in range(len(trainingSet)):
        dist = euclideanDistance(testInstance, trainingSet[x], length)
        distances.append((trainingSet[x], dist))
        distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors

# We can test out this function as follows:

trainSet = [[2, 2, 2, 'a'], [4, 4, 4, 'b']]
testInstance = [5, 5, 5]
k = 1
neighbors = getNeighbors(trainSet, testInstance, 1)
print(neighbors)

[[4, 4, 4, 'b']]

In [21]:
import operator
def getResponse(neighbors):
    classVotes = {}
    for x in range(len(neighbors)):
        response = neighbors[x][-1] # -1 c'est la dernière colonne
        if response in classVotes:
            classVotes[response]+=1
        else : 
            classVotes[response]=1    
            
    sortedVotes = sorted(classVotes.items(), key=operator.itemgetter(1), reverse=True)
    return sortedVotes[0][0]

neighbors = [[1,1,1,'a'], [2,2,2,'a'], [3,3,3,'b']]
response = getResponse(neighbors)
print(response)

a

In [23]:
def getAccuracy(testSet, predictions):
    correct = 0
    for i in range(len(testSet)):
        if (testSet[i][-1]==predictions[i]):
            correct+= 1   
    return (correct/float(len(testSet))) * 100.0


testSet = [[1,1,1,'a'], [2,2,2,'a'], [3,3,3,'b']]

predictions = ['a', 'a', 'a']

accuracy = getAccuracy(testSet, predictions)

print(accuracy)

66.66666666666666